### ISSUE TITLE
Fail in joomla 3.6 and 3.6.1 versions can you recheck?

### ISSUE THREAD

**Issue by faralai** [ElevenPaths/latch-plugin-joomla#14]

**Comment by jaesga** [comment]
Hi Faralai,

As far as we know this plugin works only for versions between 2.5 and 3.4.8. 
We have limited resources to maintain compatibility for plugins with the newer versions but we will try to do our best in order to fix this issue. 

Feel free to contribute with a pull request if you want to make this plugin compatible with the latest Joomla version. 

Thanks for your report and your interest in Latch.
Kindly regards.

**Comment by erick-christian** [comment]
Saddly it brokes my Site (Joomla 3.6.4). Now I can't access the Admin Page (Administrator), it throws an error 500.

Time to restore a Backup!

Let's try if I can find out how to fix it!

**Comment by jaesga** [comment]
Sorry for our late response, 

@erick-christian  Can you check this pull-request (already merged), maybe it fix your problem.

https://github.com/ElevenPaths/latch-plugin-joomla/pull/15

Regards,
Javi.

**Comment by phproberto** [comment]
Latest version works with latest joomla release. Closing this
